name: "Check for new version"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  new-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4
          pip install requests
      - name: check for new version
        env:
          GH_TOKEN: ${{ github.token }}
        id: check
        run: |
          proceed=0
          ./new-version.py --check
          if [ -f ./latest_version ]; then
            latest_version=$(cat ./latest_version)
            echo "latest_version=${latest_version}" >> $GITHUB_OUTPUT
            if [ $(gh pr list --search "$latest_version }} in:title" | wc -l) -eq 0 ]; then
              echo "no existing PR"
              if [ $(git branch -l | grep $latest_version | wc -l) -eq 0 ]; then
                echo "no existing branch"
                proceed=1
              fi
            fi  
          fi
          rm -f ./latest_version
          echo "proceed=${proceed}" >> $GITHUB_OUTPUT
          echo "proceed = ${proceed}"
      - name: set-up git
        if: steps.check.outputs.proceed == '1'
        run: |
          git config --global user.email "neilmunday@users.noreply.github.com"
          git config --global user.name "Neil Munday"
      - name: create branch for new version
        if: steps.check.outputs.proceed == '1'
        run: |
          git checkout -b "${{ steps.check.outputs.latest_version }}"
      - name: update version to latest
        if: steps.check.outputs.proceed == '1'
        run: |
          ./new-version.py
      - name: commit changes
        if: steps.check.outputs.proceed == '1'
        run: |
          git commit -a -m "Update SLURM version to ${{ steps.check.outputs.latest_version }}"
          git push --set-upstream origin "${{ steps.check.outputs.latest_version }}"
      - name: create pull request
        if: steps.check.outputs.proceed == '1'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create -a neilmunday -f
